export const ADD_MENU_ELEMENT = "ADD_MENU_ELEMENT";
export const REMOVE_MENU_ELEMENT = "REMOVE_MENU_ELEMENT";

export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";